// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqL-Gq32-OAlmt4knPmaqZdCE4sNkK8FQ',
    appId: '1:236488359466:web:aff3dba755bc9f49c28d53',
    messagingSenderId: '236488359466',
    projectId: 'final-project---test',
    authDomain: 'final-project---test.firebaseapp.com',
    databaseURL: 'https://final-project---test-default-rtdb.firebaseio.com',
    storageBucket: 'final-project---test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO4LsNbeijzC9rCNoEO9F_Z2yN1DGUHOw',
    appId: '1:236488359466:android:1be1ad55f617e24dc28d53',
    messagingSenderId: '236488359466',
    projectId: 'final-project---test',
    databaseURL: 'https://final-project---test-default-rtdb.firebaseio.com',
    storageBucket: 'final-project---test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLK_dQbr6SNC_oHh3CnCv-fuGhNqNx9-U',
    appId: '1:236488359466:ios:be0be2b8148d27c1c28d53',
    messagingSenderId: '236488359466',
    projectId: 'final-project---test',
    databaseURL: 'https://final-project---test-default-rtdb.firebaseio.com',
    storageBucket: 'final-project---test.appspot.com',
    iosBundleId: 'com.example.flutNex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLK_dQbr6SNC_oHh3CnCv-fuGhNqNx9-U',
    appId: '1:236488359466:ios:be0be2b8148d27c1c28d53',
    messagingSenderId: '236488359466',
    projectId: 'final-project---test',
    databaseURL: 'https://final-project---test-default-rtdb.firebaseio.com',
    storageBucket: 'final-project---test.appspot.com',
    iosBundleId: 'com.example.flutNex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqL-Gq32-OAlmt4knPmaqZdCE4sNkK8FQ',
    appId: '1:236488359466:web:8eeb836aff0d6e68c28d53',
    messagingSenderId: '236488359466',
    projectId: 'final-project---test',
    authDomain: 'final-project---test.firebaseapp.com',
    databaseURL: 'https://final-project---test-default-rtdb.firebaseio.com',
    storageBucket: 'final-project---test.appspot.com',
  );

}